---
title: "Modelling and Prediction"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)
```

```{r load-packages, echo=T, message=F, warning=F}

library(haven)
library(readxl)
library(tidyverse)
library(lubridate)
library(rsample)
library(recipes)
library(parsnip)
library(yardstick)
library(ranger)
```

```{r reshape-data, echo=T, message=F, warning=F}

# read in data
claims_data <- read_csv("data/clean/merged.csv")
date_var <- read_excel("abc.xlsx")

# reshape data to long (kind of)
initial_long <- claims_data %>%
  pivot_longer(cols = 
                 initial_claims_2020_01_04:initial_claims_2020_04_18, 
               names_to = "initial_type", values_to = "initial_num") %>%
  left_join(date_var)

continued_long <- claims_data %>%
  pivot_longer(cols = 
                 continued_claims_2020_01_04:continued_claims_2020_04_18,
               names_to = "continued_type", values_to = "continued_num") %>%
  left_join(date_var) %>%
  select(state, date, continued_type, continued_num)

claims_long <-
  left_join(initial_long, continued_long, by = c("state","date"))
anti_join(initial_long, continued_long)

# select variables
claims_long <- claims_long %>%
  select(initial_type, initial_num, continued_type.x, continued_num, 
         date, sah_date, days_since_peak_deaths, Incident_Rate, 
         Mortality_Rate, region, topind_gdp, topindemp_1, topindemp_2, 
         topindemp_3, totpop_2018, pctpop_work, pctpop_hs, 
         personal_inc2019, gov_republican, state) %>%
  mutate(days_since_sah = as.Date(date) - ymd(sah_date)) %>%
  mutate(days_since_sah = replace_na(days_since_sah, 0)) %>%
  mutate(days_since_peak =
           days_since_peak_deaths - (as.Date("2020-05-01") - as.Date(date))) %>%
  mutate(gov_republican = factor(gov_republican)) %>%
  filter(as.Date(date) >= as.Date("2020-03-21")) %>%
  select(-sah_date, -days_since_peak_deaths)
```

```{r split-and-preprocess-data-for-rf, echo=T, message=F, warning=F}

set.seed(20200505)

# split data into training and test sets
claims_training <- claims_long %>%
  filter(date < ymd("2020-04-18"))
claims_testing <- claims_long %>%
  filter(date >= ymd("2020-04-18"))

# create recipe for rf
recipe_claims <- recipe(formula = initial_num ~ continued_num + 
                          days_since_sah + days_since_peak + 
                          Incident_Rate + Mortality_Rate + 
                          region + topind_gdp + topindemp_1 + topindemp_2
                        + topindemp_3 + totpop_2018 + pctpop_work + 
                          pctpop_hs + personal_inc2019 + gov_republican,
                        data = claims_training) %>%
  step_string2factor(region, topind_gdp, topindemp_1, topindemp_2, topindemp_3) %>%
  prep()

# create 10-fold
claims_resamples <- vfold_cv(data = claims_training, v = 10)
```

```{r create-custom-function-for-resamples, echo=T, message=F, warning=F}

# create custom function
train_claims <- function(model, split, try, tree) {
  
  # create analysis data from split
  claims_analysis <- analysis(split)
  
  # set models - Random Forest and CART
  if(model == "rf") {
    model_claims <- rand_forest(mode = "regression",
                                mtry = try,
                                trees = tree) %>%
      set_engine("ranger",
                 importance = "impurity") %>%
      fit(formula = initial_num ~ continued_num + days_since_sah + 
            days_since_peak + Incident_Rate + Mortality_Rate + region + 
            topind_gdp + topindemp_1 + topindemp_2 + topindemp_3 + 
            totpop_2018 + pctpop_work + pctpop_hs + personal_inc2019 + 
            gov_republican,
          data = bake(object = recipe_claims,
                      new_data = claims_analysis))
  }
  else if(model == "cart") {
    model_claims <- decision_tree(mode = "regression") %>%
      set_engine("rpart") %>%
      fit(formula = initial_num ~ continued_num + days_since_sah + 
            days_since_peak + Incident_Rate + Mortality_Rate + region + 
            topind_gdp + topindemp_1 + topindemp_2 + topindemp_3 + 
            totpop_2018 + pctpop_work + pctpop_hs + personal_inc2019 + 
            gov_republican,
          data = bake(object = recipe_claims,
                      new_data = claims_analysis))
  }
  
  # create assessment data from split
  claims_assessment <- assessment(split)
  
  # get predictions on assessment data and rmse for each split
  rmse <- bind_cols(
    claims_assessment,
    predict(model_claims, bake(object = recipe_claims,
                               new_data = claims_assessment))) %>%
    rmse(truth = initial_num, estimate = .pred) %>%
    pull(.estimate)
  
  return(rmse)
}
```

```{r pick-model, echo=T, message=F, warning=F}

# apply custom function to resamples
claims_resamples <- claims_resamples %>%
  mutate(
    rmse_rf_1 = map_dbl(.x = splits,
                        .f = ~train_claims(model = "rf",
                                           split = .x,
                                           try = 5,
                                           tree = 50))
  ) %>%
  mutate(
    rmse_rf_2 = map_dbl(.x = splits,
                        .f = ~train_claims(model = "rf",
                                           split = .x,
                                           try = 10,
                                           tree = 50))
  ) %>%
  mutate(
    rmse_rf_3 = map_dbl(.x = splits,
                        .f = ~train_claims(model = "rf",
                                           split = .x,
                                           try = 5,
                                           tree = 100))
  ) %>%
  mutate(
    rmse_cart = map_dbl(.x = splits,
                        .f = ~train_claims(model = "cart",
                                           split = .x))
  )

glimpse(claims_resamples)

# compare rf and cart
claims_resamples <- claims_resamples %>%
  select(-splits)

knitr::kable(claims_resamples)
knitr::kable(rmse_avg <- c(mean(claims_resamples$rmse_rf_1),
                           mean(claims_resamples$rmse_rf_2),
                           mean(claims_resamples$rmse_rf_3),
                           mean(claims_resamples$rmse_cart)),
             col.names = "RMSE"
)
```

```{r visualize-RMSEs-for-resamples, echo=T, message=F, warning=F}

claims_resamples %>%
  pivot_longer(-id) %>%
  ggplot(aes(x = id,
             y = value,
             color = name,
             group = name)) +
  geom_point() +
  geom_line() +
  scale_y_continuous(limits = c(0, NA)) +
  theme_minimal()
```

```{r est-out-of-sample-rate, echo=T, message=F, warning=F}

# prediction on testing data
model_final <-
  rand_forest(mode = "regression",
              mtry = 5,
              trees = 50) %>%
  set_engine("ranger",
             importance = "impurity") %>%
  fit(initial_num ~
        continued_num +
        days_since_sah + days_since_peak + Incident_Rate + Mortality_Rate
      + region + topind_gdp + topindemp_1 + topindemp_2 + topindemp_3 + 
        totpop_2018 + pctpop_work + pctpop_hs + personal_inc2019 +
        gov_republican,
      data = bake(object = recipe_claims,
                  new_data = claims_training))

# add predicted values column to testing data
claims_testing <- bind_cols(
  claims_testing,
  pred_claims_2020_04_18 = predict(model_final, claims_testing)
) 

# Error metric estimation
bind_cols(
  claims_testing,
  pred_claims_2020_04_18 = predict(model_final, claims_testing)
) %>%
  metrics(truth = initial_num, 
          estimate = .pred)
```
