---
title: "Random Forest Model Building"
author: "Radhika Kaul, Odiche Nwabuikwu, Ruochen Wang"
date: "5/3/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)
```

### Details about the dataset 

```{r data_description}
library(knitr)
library(kableExtra)
library(readxl)

codebook <- read_excel("data/raw/codebook.xlsx")

# Creating HTML friendly table
codebook %>%
  kable() %>%
  kable_styling()

```

### Loading required R packages
```{r load packages}
library(tidyverse)
library(caret)
library(readr)
library(ggplot2) 
library(ggthemes)
library(dplyr) 
library(lubridate) # for manipulation of dates
library(rpart) 
library(rsample)
library(recipes)
library(parsnip)
library(yardstick)
library(ranger)

```

### Loading and Preparing data

```{r Load data}

# Load the data
merged <- read.csv("data/clean/merged.csv")
head(merged)
str(merged) # to get the structure of the datatset

# Inspect the data
summary(merged)

# Split the data into training and test set
set.seed(1234)

# Create a split object - in ratio of 80:20
split <- initial_split(merged, prop = 0.8)

# Using split object to create testing and training data
train.data <- training(split)
test.data <- testing(split)

data_resamples <- vfold_cv(data = train.data, v = 10)
```


### Pre-processing the data

```{r data pre-process}

## Merge it with Odiche and Ruochen's pre-processing code

```

### Training the model and making predictions



### ### Tuning the parameters - Best tuning parameter mtry - i don't quite understand this

```{r Predictions}

# Make predictions on the test data
pred_results <- predict(train.data,
                        test.data,
                        type = "raw") # generates predictions in terms of raw numbers or classes.

pred_df <- data.frame(pred_results)

valid_verify_df <- cbind(test.data$`initial_claims_2020-04-04`,pred_df)
head(valid_verify_df)
```

### Defining and visualizing variable importance
